### ISSUE TITLE
Image gets deleted

### ISSUE THREAD

**Issue by ChunkyTester** [b3nab/instapy-cli#22]
After the image is uploaded to instagram it gets deleted from the local storage of computer.

How do i stop it from happening.

In media.py of this repo i found this
def removeMedia(self):
        os.remove(self.pathFile)

Help would be appreciated

**Comment by b3nab** [comment]
I managed to delete only files downloaded. 
I'm rejecting zimy pull request because it only remove the line that delete file, but this is not the purpose of this library. The files that already are on disk aren't touched, but the files downloaded with this library needs to be removed. So if you use instapy on a server it won't add junks to your folders and reduce disk space usage in long-term.

In half an hour I'm going to release a new update so all of you can download the version 0.0.6
🥂
