### ISSUE TITLE
Hashtags are blocked

### ISSUE THREAD

**Issue by cagrio** [b3nab/instapy-cli#3]
Hey I experienced the following problem.
I upload the picture with hashtag H from account X. Account Y doesnt follow account X and cant see the uploaded picture from under hashtag H. However when its uploaded using Ramme, picture is visible for account Y under hashtag H.

**Comment by b3nab** [comment]
Hi @cagrio ! Thanks for reaching out. I suggest you to repeat the test and check the account validity. I checked out and no problems for me.

instapy-cli returns some errors?

**Comment by cagrio** [comment]
no no it doesn't return any error. It works perfectly except one thing. By the way have you validate your account with phone number?

**Comment by g-bon** [comment]
@cagrio I think there is a misunderstanding here, this is just a client to post instagram photos from command line. Anything concerning account, photos visibility, permissions etc. belong to instagram itself and there is no power here to do anything about it. You should use official instagram support or help for those kind of questions.

**Comment by b3nab** [comment]
Yes, as stated by @g-bon , any problems about instagram should concern instagram's support.
I tried with an old account I have, but no problems jumps out and the hashtag gallery were populated with my photo as expected.

However yestarday I tried with these steps:
- create a new instagram account and set public profile
- upload a photo with instapy-cli

The new photo has your same problem because it did not figure out on hashtag photo gallery. So, I think that you need to upload your first photo with instagram app or do something others than upload a photo, or maybe the new account need to wait some time (probably?).

I don't know how Ramme works, but I think that this problem is because of using instagram private api and using it with new accounts. 
If you want to do other tests all the community will appreciate. :)

For now I'm closing this issue. Thanks all for supporting instapy-cli. 🎉
