### ISSUE TITLE
Asyncronous upload

### ISSUE THREAD

**Issue by giorizzotti** [b3nab/instapy-cli#38]
With the latest version of the library (released just a a couple of hours ago), I'm trying to upload images in my story, but I need to preserve order, so I'm trying with time.sleep(1), but it doesn't works, order is almost random.
This is the code:
```python
with client(config.instagram_username, config.instagram_password) as cli:    
   for i in range(0, len(image_files)):
     cli.upload(image_files[i], story=True)
     time.sleep(1)

```
What can I try? Python 3.7.1

**Comment by b3nab** [comment]
The first thing I thought was an error on python arrays, but your code seems to be fine except the `time.sleep(1)`.

I suppose it is a too short time to wait. Imagine how you do with the Instagram app, at least 5 to 10 seconds are needed to create a story, publish it and do it again.
I think that in order to prevent ban or soft ban (only some actions are forbidden for a short period of time) you should avoid any inconsistencies during the upload phase. So simulate a more consistent waiting time should solve your problem.

**Comment by b3nab** [comment]
I tried your code, just add some prints:
```python
with client(username, password) as cli:
    for i in range(0, len(image_files)):
        print('image: ', image_files[i])
        res = cli.upload(image_files[i], story=True)
        print('IG: >> ', res)
        time.sleep(1)
```

1st try: it works very well, 4 images all in order.
2nd try: the first and the second image are inverted, other twos are ok.
3rd try: all ok and in order.

So I think that if you care a lot about order and want to post a lot of content in a short range of time, you need to think and build a good time management strategy into your code.
